[package]
name = "gate"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gatehouse-proto.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
clap.workspace = true
base64.workspace = true
rand.workspace = true
